[build]
  command = "npm run build"
  publish = "build"

# Zorg dat alle routes via de SvelteKit-server gaan
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  external_node_modules = ["@supabase/supabase-js"]
  node_bundler = "esbuild"
